server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/book_reader
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=5GB
spring.servlet.multipart.max-request-size=5GB

token.signing.key=3c469e9d6c5875d37a43f353d4f88e61fcf812c66eee3457465a40b0da4153e0
